### ISSUE TITLE
[Docs] OIDC Federation

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-cie-oidc-java#11]
You have to indicate in the readme what has been implemented by OIDC Federation.

For example, explicit client registration workflow was not implemented.

It is useful to indicate if the implementation of OIDC Federation can be fine for any type of entity or if it is narrowed on this RP.

**Comment by mmariuzzo** [comment]
If "client registration" means "interactive on-boarding" this aspects on the RP side is implemented both in the library and in the spring boot example (as described in the [README](https://github.com/italia/spid-cie-oidc-java/blob/main/examples/relying-party-spring-boot/README.md))

**Comment by mmariuzzo** [comment]
Documentation is still WIP. I will extend it to make it more clear also on this aspect

**Comment by peppelinux** [comment]
client registration is something that happens OP side, once the trust have been establoshed to a requester RP

the onboarding is instead the way a TA (federation authority) include a participant (entity) in a federation

**Comment by mmariuzzo** [comment]
In the documentation we state only RP side is implemented, at the moment.
