### ISSUE TITLE
Fix test for "expiresOn" 

### ISSUE THREAD

**Issue by mmariuzzo** [italia/spid-cie-oidc-java#17]
Fields `issuedAt` and `expiresOn` are DateTime with seconds precision. 

We cannot use "now" to test expiration because test fails on fast machines

**Comment by peppelinux** [comment]
in IAM products is often adopted a confidence time, usually 5 minutes, within which time deltas are managed

**Comment by mmariuzzo** [comment]
Right. But the problem was inside the testing code of the expiresOn field as a LocalDateTime element with seconds precision
