### ISSUE TITLE
GET /oidc/rp/ errore 404  

### ISSUE THREAD

**Issue by frhack** [italia/spid-cie-oidc-java#19]
Ho seguito queste istruzioni: https://github.com/italia/spid-cie-oidc-java/tree/main/examples/relying-party-spring-boot

ma il web server risponde errore 404 
Quale può essere il problema ?

Grazie !

```
 wget http://127.0.0.1:8080/oidc/rp/
--2023-02-15 13:22:40--  http://127.0.0.1:8080/oidc/rp/
Connecting to 127.0.0.1:8080... connected.
HTTP request sent, awaiting response... 404
2023-02-15 13:22:40 ERROR 404: (no description).
```

log: 
`
WARN 37662 --- [nio-8080-exec-1] o.s.web.servlet.PageNotFound             : No mapping for GET /oidc/rp/
 
`

**Comment by mmariuzzo** [comment]
Ciao, 

la guida presenta diversi passi. Quando esattamente ottieni l'errore?

Nella console del processo java, la fine dell'avvio dello SpringBoot dovrebbe essere testimoniato da queste 3 righe di log

```
2023-02-20 20:07:33.382  INFO 295437 --- [           main] i.s.c.o.s.b.r.party.RelyingPartyWrapper  : final jwk: 
2023-02-20 20:07:33.383  INFO 295437 --- [           main] i.s.c.o.s.b.r.party.RelyingPartyWrapper  : final trust_marks: 
2023-02-20 20:07:33.664  INFO 295437 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
```

**Comment by frhack** [comment]
> Ciao,
> 
> la guida presenta diversi passi. Quando esattamente ottieni l'errore?
> 
> Nella console del processo java, la fine dell'avvio dello SpringBoot dovrebbe essere testimoniato da queste 3 righe di log
> 
> ```
> 2023-02-20 20:07:33.382  INFO 295437 --- [           main] i.s.c.o.s.b.r.party.RelyingPartyWrapper  : final jwk: 
> 2023-02-20 20:07:33.383  INFO 295437 --- [           main] i.s.c.o.s.b.r.party.RelyingPartyWrapper  : final trust_marks: 
> 2023-02-20 20:07:33.664  INFO 295437 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
> ```

ciao grazie, ho risolto il problema. Ho adottato una una procedura leggermente modificata rispetto alle istruzioni:

Lanciare la federation_authority del progetto django:

`spid-cie-oidc-django/examples/federation_authority$ ./manage.py runserver 0.0.0.0:8000
`
quindi lancio il relying-party-spring-boot

`spid-cie-oidc-java/examples/relying-party-spring-boot$ ../../mvnw clean spring-boot:run
`
Mi interessava non usare docker in modo da poter fare sviluppo sul progetto java, ovvero modificare i sorgenti agevolmente.

Pensavo che l'errore che avevo era dovuto al "not found" che si ha con l'url del subject  http://127.0.0.1:8080/oidc/rp/
ma non era quello il problema visto che ora funziona tutto e il not found rimane.

Forse è un po' fuorviante e che interrogando l'url del subject si abbia un errore 404 not found

**Comment by mmariuzzo** [comment]
Ciao, felice che tu abbia superato il problema.

Stavo però osservando che nella guida è indicato di accedere a "http://127.0.0.1:8080/oidc/rp/". La url di accesso ha un "/landing" alla fine.

Sarà onere di un eventuale reverse-proxy forwardare  "http://127.0.0.1:8080/oidc/rp/" verso "http://127.0.0.1:8080/oidc/rp/landing".

Se mi confermi, procedo a chiudere il ticket

**Comment by frhack** [comment]
> Se mi confermi, procedo a chiudere il ticket

ok chiudi pure, grazie !
