### ISSUE TITLE
Informazione sui rilasci/aggiornamenti

### ISSUE THREAD

**Issue by netlogo-it** [italia/spid-cie-oidc-java#21]
Buongiorno, noto che il codice sorgente non riceve aggiornamenti dal 21 Aprile 2022 (ultima release 0.2.1), nonostatante vi siano degli aggiornamenti sul documento ufficiale riguardante le specifiche tecniche (ultimo aggiornamento 07 Marzo 2023).
Volendo realizzare un nostro RP utilizzando la libreria di base (starker-kit) mi chiedo se la stessa può essere utilizzata in ambiente di produzione e se verrà aggiornata nel tempo man mano che le specifiche AgID lo richiederanno.

**Comment by rglauco** [comment]
Buongiorno [la versione 1.0.0](https://github.com/italia/spid-cie-oidc-java/releases/tag/v1.0.0), appena rilasciata è stata testata nell'onboarding di Federazione CIE inclusi i test di logon/logoff. Nel file README.md dell'applicazione di esempio, trova alcuni suggerimenti utili a passare la fase di onboarding.
