### ISSUE TITLE
Entity Configuration claims typ mancante

### ISSUE THREAD

**Issue by ebusi** [italia/spid-cie-oidc-java#30]
L'header del EC in formato JWT non contiene la claim "typ" che invece è presente in tutti gli esempi della documentazione e sembra anche essere richiesta e validata in fase di federazione CIE.

https://github.com/italia/spid-cie-oidc-java/blob/70779edf007876b0bb1f9fd5ddacdf108338b899/starter-kit/src/main/java/it/spid/cie/oidc/helper/JWTHelper.java#L442

**Comment by rglauco** [comment]
fixed in https://github.com/italia/spid-cie-oidc-java/pull/32
