### ISSUE TITLE
[Doc] provide an animated gif of an example auth

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-cie-oidc-java#8]
# [Doc] provide an animated gif of an example auth

as made here
https://github.com/italia/spid-cie-oidc-php#spidcie-oidc-federation-relying-party-for-php

**Comment by peppelinux** [comment]
@mmariuzzo can we close this issue?

Usually we put the pr or commit that closed it

**Comment by mmariuzzo** [comment]
I will close after the publication of a second gif for the onboarding flow. Actually it is descried only as bulleted list.

**Comment by mmariuzzo** [comment]
Instead of a gif, a youtube video with the full flow (on-boarding, login, loguot) is available from the example README
